---
name: httpd_ctl
version: 1.05
author: []
abstract: |-
  An apache httpd control script that supports Template Toolkit
  pre-processing
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Basename: 0
  File::Which: 0
  Getopt::Long: 0
  IO::All: 0
  Log::Dispatch::Email::MIMELite: 0
  Log::Log4perl: 0
  Pod::Usage: 0
  Proc::Reliable: 0
  Switch: 0
  Template: 0
  perl: 5.006
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
